# Workspace for Fourier Tasks

- By: (redacted), 2025
- Corresponding paper (redacted), 2026
- Licence: MIT
- [Click here for the Fourier source repository (redacted)](https://fake.url)
- [Based on the DCDHCS repo](https://github.com/MarkGotham/Data_Compression)

In [2]:
import numpy as np

---

## Background

While there's very little assumed knowledge in this course,
it would be useful to make sure you're comfortable with
basic mathematical operations on matrices.

This notebook provides a 'sandpit' for trying things out.
The demos below cover scalar operations, dot products, and array indexing —
all of which appear throughout the Fourier material.
The tasks at the bottom move things on a bit further.

## Task

- Type: Implement

- Tasks: Write functions to ...
  1. Get the `shape` (m- and n-dimensions) of any 1- or 2-D array.
  2. 'Pad' (expand) an array to double the length and width (4× the size in total) with zeros to the right and below.
  3. Reduce an array to half the length and width (1/4 total), taking the top-left block.
  4. Implement the dot product for two equal-length 1-D arrays from scratch.

- Reference implementations provided below:
  1. `get_m_n()`
  2. `pad_2x2()`
  3. `back_to_half()` (complements `pad_2x2`)
  4. `dot_from_scratch()`, plus NumPy equivalents `np.dot(a, b)`, `np.matmul(a, b)`, `a @ b`.
     - Bonus: verify with `np.allclose`.

---
# Demos

Work through these before attempting the tasks.

## Scalar operations

Adding, subtracting, multiplying, or dividing by a scalar
applies that operation to every entry in the array.

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a + 1

array([2, 3, 4])

In [4]:
a - 1

array([0, 1, 2])

In [5]:
a * 2

array([2, 4, 6])

In [6]:
a / 2

array([0.5, 1. , 1.5])

## Dot product

This section covers the difference between:

- element-wise multiplication (returns an array)
- the dot product: sum of element-wise products (returns a scalar for 1-D inputs)

Note that `a` is unchanged by the scalar operations above:

In [7]:
a

array([1, 2, 3])

In [8]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [9]:
a * b  # element-wise multiplication — returns an array

array([ 4, 10, 18])

In [10]:
sum(a * b)  # summing element-wise products gives the dot product

32

NumPy provides three equivalent ways to compute the dot product for 1-D arrays:

In [11]:
a @ b

32

In [12]:
np.dot(a, b)

32

In [13]:
np.matmul(a, b)

32

For 2-D arrays `@` and `np.matmul` perform full matrix multiplication.
Each entry $(i, j)$ of the result is the dot product of row $i$ of the left matrix
and column $j$ of the right matrix:

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B   # E.g, entry (0,0) = 1*5 + 2*7 = 19

array([[19, 22],
       [43, 50]])

## Indexing (part of an array)

In [20]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
c[0, 1]  # single position: row 0, column 1

1

In [28]:
c[1, 0:4]  # second row (index 1)

array([4, 5, 6, 7])

In [23]:
c[1,]  # equivalent shorthand for the full second row

array([4, 5, 6, 7])

In [31]:
c[0:4, 1]  # second column (index 1)

array([ 1,  5,  9, 13])

In [32]:
c[1::]  # from row 1 onwards (skips the first row)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
c[::2]  # every other row

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [34]:
c[0:2, 0:2]  # top-left 2×2 block

array([[0, 1],
       [4, 5]])

In [38]:
c[1]

array([4, 5, 6, 7])

## A note on (2) dimensions

In NumPy, arrays are indexed as `(row, column)` — i.e. `(m, n)`. This:
- matches matrix / linear-algebra notation
- matches plain Python lists-of-lists (as below)
- differs from Cartesian `(x, y)` coordinates, which are the other way round

In [35]:
list_of_lists = [[0, 1, 2], [3, 4, 5]]
list_of_lists[1][0]   # I.e., row 1, column 0  which is  3

3

In [36]:
np.array(list_of_lists)[1][0]  # same result with a NumPy array

3

---
## Workspace

In [9]:
a_1d = np.array(
    [1, 2, 3]
)
len(a_1d.shape)

1

In [ ]:
# Task 1
a_2d = np.array([[1., 1., 1., 1., 1.],
                 [1., 1., 1., 1., 1.],
                 [1., 1., 1., 1., 1.]])

def get_m_n(a):
    a = np.array(a)
    s = a.shape
    if len(s) == 1:
        return s[0], 1
    elif len(s) == 2:
        return s
    elif len(s) > 2:
        raise ValueError("Input must be 1D or 2D!")
get_m_n()

ValueError: Input must be 1D or 2D!

In [51]:
# Task 2
a_2d = np.array([[2, 3, 4],
                 [1, 5, 7],
                 [2, 4, 1]])
def pad_2x2(m):
    assert m.ndim == 2
    m = np.array(m)
    m = np.pad(m, ((0, m.shape[0]), (0, m.shape[1])), mode="constant", constant_values=0)
    return m

pad_2x2(
    a_2d
)
    

array([[2, 3, 4, 0, 0, 0],
       [1, 5, 7, 0, 0, 0],
       [2, 4, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
# Task 3
arr = np.array(
    [[2, 3, 4, 0, 0, 0],
       [1, 5, 7, 0, 0, 0],
       [2, 4, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
def back_to_half(m):
    assert m.ndim == 2
    x, y = get_m_n(m)
    return m[0:x // 2, 0:y // 2] # also do it with np.pad?

back_to_half(arr)

array([[2, 3, 4],
       [1, 5, 7],
       [2, 4, 1]])

In [ ]:
# Task 4
def dot_from_scratch(m1, m2):
    assert len(m1) == len(m2)

    return sum(m1[i] * m2[i] for i in range(len(m1)))



---

## Reference

### Task 1 — `get_m_n`

In [37]:
def get_m_n(a: np.ndarray) -> tuple:
    """
    Return the (m, n) dimensions of a 1- or 2-D array.

    For a 1-D array of length m, returns (m, 1).
    For a 2-D array, returns (rows, columns).
    Raises ValueError for arrays with 3 or more dimensions.

    :param a: Input array, 1-D or 2-D.
    :return: (m, n) tuple of ints.
    """
    s = a.shape
    if len(s) == 1:
        return s[0], 1
    elif len(s) == 2:
        return s[0], s[1]
    else:
        raise ValueError("Input must be 1-D or 2-D.")

In [53]:
a_2d = np.array([[1., 1., 1., 1., 1.],
                 [1., 1., 1., 1., 1.],
                 [1., 1., 1., 1., 1.]])
print(get_m_n(a_2d))  # (3, 5)

(3, 5)


In [38]:
a_1d = np.array([1, 2, 3, 4, 5, 6])
print(get_m_n(a_1d))  # (6, 1)

(6, 1)


### Task 2 — `pad_2x2`

In [39]:
def pad_2x2(a: np.ndarray) -> np.ndarray:
    """
    Pad a 2-D array to double the length and width (4× total size)
    by appending zeros to the right and below.

    `np.pad` takes a sequence of (before, after) pairs, one per axis:
    [(0, x), (0, y)] means 'add x rows below and y columns to the right,
    nothing before'.

    :param a: 2-D input array of shape (m, n).
    :return: Zero-padded array of shape (2m, 2n).
    """
    assert a.ndim == 2, "Input must be a 2-D array."
    x, y = get_m_n(a)
    return np.pad(
        a,
        [(0, x), (0, y)],   # (before, after) for each axis
        mode='constant',
        constant_values=0
    )

In [46]:
reference = [[1, 0]]
print(
    f"Padding {reference}:\n",
    pad_2x2(np.array(reference))
)

Padding [[1, 0]]:
 [[1 0 0 0]
 [0 0 0 0]]


In [47]:
reference = [[1], [0]]
print(
    f"Padding {reference}:\n",
    pad_2x2(np.array(reference))
)

Padding [[1], [0]]:
 [[1 0]
 [0 0]
 [0 0]
 [0 0]]


In [48]:
reference = [[1, 0], [0, 1]]
print(
    f"Padding {reference}:\n",
    pad_2x2(np.array(reference))
)

Padding [[1, 0], [0, 1]]:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Task 3 — `back_to_half`

In [49]:
def back_to_half(a: np.ndarray) -> np.ndarray:
    """
    Reduce a 2-D array to half the length and width (1/4 total size)
    by returning the top-left block. Complements `pad_2x2`.

    Requires even dimensions.

    :param a: 2-D input array of shape (m, n) where m and n are even.
    :return: Top-left block of shape (m//2, n//2).
    """
    assert a.ndim == 2, "Input must be a 2-D array."
    x, y = get_m_n(a)
    assert x % 2 == 0 and y % 2 == 0, "Both dimensions must be even."
    return a[0:x // 2, 0:y // 2]

In [44]:
a_padded = np.array([[1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 0, 0],
                     [0, 0, 0, 0]])
back_to_half(a_padded)

array([[1, 0],
       [0, 1]])

In [ ]:
# Roundtrip test: pad then halve. End result should match the original exactly.
a = np.array([[1, 0], [0, 1]])
p = pad_2x2(a)
halved = back_to_half(p)
np.allclose(halved, a)

### Task 4 — `dot_from_scratch`

In [67]:
def dot_from_scratch(
        a: np.ndarray,
        b: np.ndarray
) -> float:
    """
    Compute the dot product of two equal-length 1-D arrays from scratch.

    Multiplies corresponding elements and sums the results,
    equivalent to np.dot(a, b) for 1-D inputs.

    :param a: 1-D array of length n.
    :param b: 1-D array of length n.
    :return: scalar dot product.
    """
    assert len(a) == len(b), "Arrays must have equal length."
    return sum(a[i] * b[i] for i in range(len(a)))

In [71]:
a = np.array([1, 2, 3, 4])
b = np.array([5, -6, 7, -8])

s = dot_from_scratch(a, b)

In [72]:
np.allclose(
    s,
    np.dot(a, b)
)

True

In [73]:
np.allclose(
    s, np.matmul(a, b)
)

True

In [74]:
np.allclose(
    s,
    a @ b
)

True

End

---